### ISSUE TITLE
How to print soap request which is sent to SOAP server?

### ISSUE THREAD

**Issue by codeforgeek** [strongloop/loopback-connector-soap#10]
i am using this code, its working fine for me.

```
    var service=ds.createModel('service',{});
        service.GetBundleList({getBundleList : {CountryCode:'USA',BrandCode:'UVA',LanguageCode:'En',ICCID:'8901260842140591893',MSISDN:'14252833121'}},function(err,response){
          console.log(response);
        });
```

It printing the response but i want to print the request to actually determine the payload of SOAP request.

**Comment by EmilTholin** [comment]
I'm kind of late to the party @codeforgeek, but you can log your dataSource after a request to look at the LastRequest like you mentioned.

**Comment by eddiemonge** [comment]
@codeforgeek did Emil's response solve your problem? Please let us know if it didn't so this can be re-opened.
