### ISSUE TITLE
Bump debug dependency to v4

### ISSUE THREAD

**Issue by 3z3qu13l** [strongloop/loopback-connector-soap#101]
Hello guys,

Is it possible to update **debug** version to latest:
https://github.com/visionmedia/debug/releases

They added node 10 support and bump vulnerable packages.
From their changelog, no breaking change :)

**Comment by 3z3qu13l** [comment]
PR merged

**Comment by dhmlau** [comment]
@3z3qu13l , any reason you want to reopen this issue?

**Comment by 3z3qu13l** [comment]
No sorry.  Probably missclick
