### ISSUE TITLE
input parameters - array

### ISSUE THREAD

**Issue by dingodingo** [strongloop/loopback-connector-soap#11]
Here is the issue I posted on the forum, but haven't got any response. So simply try here. Your help will be really appreciated.

https://groups.google.com/forum/#!topic/loopbackjs/IX2yKCevDeI

**Comment by eddiemonge** [comment]
@dingodingo Can you verify if this is still a problem please?

**Comment by superkhau** [comment]
@dingodingo I'm gonna close this issue since it's 2 years old. If you are still running into issues, please open a new one.
