### ISSUE TITLE
Spike for: Support for SOAP 1.2

### ISSUE THREAD

**Issue by dashby3000** [strongloop/loopback-connector-soap#15]
Enhanced SOAP connector - Shelby enhanced the SOAP connector to handle WSDL 1.2/2.0, we want bake this back into the SL Connector.

Please reference: https://github.com/shelbys/loopback-connector-soap

ref: PLATAPI-1480

**Comment by chandadharap** [comment]
I don't think this should be labelled as critical.

**Comment by chandadharap** [comment]
This is not a simple matter of merge. Needs working out of a solution.

**Comment by chandadharap** [comment]
Needs a XS spike.

**Comment by chandadharap** [comment]
status please?

**Comment by raymondfeng** [comment]
An issue was identified in node-soap. I created a fix in our folk and it has been verified by GoDaddy. We'll add a test case and submit a patch to upstream. The spile can be closed.
