### ISSUE TITLE
Ability to define SOAP datasources and models using loopback's json definition format

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-soap#17]
It seems the only way to define a SOAP datasource and model at the moment is to do it in a boot script, which is inconsistent with the way that the rest of our app is defined using Loopback's json definition files. This means that the definition of our datasources and models is now spread around the codebase rather than being consolidated in a single place (/datasources.json, /model-config.json and /common/models), which isn't ideal.

Can the soap connector be made to support the standard way of defining models and datasources too?

**Comment by raymondfeng** [comment]
It's already doable using `slc loopback:datasource` and `slc loopback:model` commands. When you define the data source, you can select the SOAP connector.

Please note that additional configuration properties such as `wsdl` need to be manually added to `server/datasources.json` after running the command line.

**Comment by mrfelton** [comment]
Setting up a SOAP datasource in this way does not appear to work. Or at least, no SOAP methods are listed in the API Explorer for the connected model.

Note, I do have the patch from https://github.com/strongloop/loopback-explorer/pull/22 applied, which works as expected when a SOAP datasource and connected model are set up in a boot script using the process outlined in the documentation for this module.

**Comment by sravya070** [comment]
I agree with mrfelton . SOAP data sources set up using "slc loopback:datasource" doesn't work (None of the SOAP methods in the wsdl  are listed in the Explorer ).
