### ISSUE TITLE
Problem consuming a SOAP WCF

### ISSUE THREAD

**Issue by cubissimo** [strongloop/loopback-connector-soap#19]
is there a way to consume WCF using this SOAP connector? 

i'm facing the below problem:

node_modules/soap/lib/client.js:233
    result = obj.Body[output.$name];

TypeError: Cannot read property 'ConsultarPorEmailResponse' of undefined

Some clues?
Very thx!

**Comment by raymondfeng** [comment]
What does your SOAP response look like? Can you share the WSDL?

**Comment by cubissimo** [comment]
offcourse! I had to cut the WSDL because it is too large.

WSDL:
  <?xml version="1.0" encoding="utf-8" ?> 
- <wsdl:definitions name="EntidadeServico" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata">
- <wsp:Policy wsu:Id="WSHttpBinding_IEntidadeServico_policy">
- <wsp:ExactlyOne>
- <wsp:All>
- <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
- <wsp:Policy>
- <sp:ProtectionToken>
- <wsp:Policy>
- <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
- <wsp:Policy>
  <sp:RequireDerivedKeys /> 
- <sp:BootstrapPolicy>
- <wsp:Policy>
- <sp:SignedParts>
  <sp:Body /> 
  <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" /> 
  </sp:SignedParts>
- <sp:EncryptedParts>
  <sp:Body /> 
  </sp:EncryptedParts>
- <sp:SymmetricBinding>
- <wsp:Policy>
- <sp:ProtectionToken>
- <wsp:Policy>
- <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
- <wsp:Policy>
  <sp:RequireDerivedKeys /> 
  </wsp:Policy>
  </sp:SpnegoContextToken>
  </wsp:Policy>
  </sp:ProtectionToken>
- <sp:AlgorithmSuite>
- <wsp:Policy>
  <sp:Basic256 /> 
  </wsp:Policy>
  </sp:AlgorithmSuite>
- <sp:Layout>
- <wsp:Policy>
  <sp:Strict /> 
  </wsp:Policy>
  </sp:Layout>
  <sp:IncludeTimestamp /> 
  <sp:EncryptSignature /> 
  <sp:OnlySignEntireHeadersAndBody /> 
  </wsp:Policy>
  </sp:SymmetricBinding>
- <sp:Wss11>
  <wsp:Policy /> 
  </sp:Wss11>
- <sp:Trust10>
- <wsp:Policy>
  <sp:MustSupportIssuedTokens /> 
  <sp:RequireClientEntropy /> 
  <sp:RequireServerEntropy /> 
  </wsp:Policy>
  </sp:Trust10>
  </wsp:Policy>
  </sp:BootstrapPolicy>
  </wsp:Policy>
  </sp:SecureConversationToken>
  </wsp:Policy>
  </sp:ProtectionToken>
- <sp:AlgorithmSuite>
- <wsp:Policy>
  <sp:Basic256 /> 
  </wsp:Policy>
  </sp:AlgorithmSuite>
- <sp:Layout>
- <wsp:Policy>
  <sp:Strict /> 
  </wsp:Policy>
  </sp:Layout>
  <sp:IncludeTimestamp /> 
  <sp:EncryptSignature /> 
  <sp:OnlySignEntireHeadersAndBody /> 
  </wsp:Policy>
  </sp:SymmetricBinding>
- <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <wsp:Policy /> 
  </sp:Wss11>
- <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
- <wsp:Policy>
  <sp:MustSupportIssuedTokens /> 
  <sp:RequireClientEntropy /> 
  <sp:RequireServerEntropy /> 
  </wsp:Policy>
  </sp:Trust10>
  <wsaw:UsingAddressing /> 
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>
- <wsp:Policy wsu:Id="WSHttpBinding_IEntidadeServico_ConsultarFornecedorDistribuidor_Input_policy">
- <wsp:ExactlyOne>
- <wsp:All>
- <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" /> 
  </sp:SignedParts>
- <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  </sp:EncryptedParts>
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
  </sp:EncryptedParts>
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>
- <wsp:Policy wsu:Id="WSHttpBinding_IEntidadeServico_ConsultarPorEmailSenhaHash_Input_policy">
- <wsp:ExactlyOne>
- <wsp:All>
- <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" /> 
  </sp:SignedParts>
- <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  </sp:EncryptedParts>
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>
- <wsp:Policy wsu:Id="WSHttpBinding_IEntidadeServico_ConsultarPorEmailSenhaHash_output_policy">
- <wsp:ExactlyOne>
- <wsp:All>
- <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" /> 
  </sp:SignedParts>
- <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  </sp:EncryptedParts>
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>
- <wsp:Policy wsu:Id="WSHttpBinding_IEntidadeServico_ConsultarPorEmailSenhaHash_GeneralFaultFault_Fault">
- <wsp:ExactlyOne>
- <wsp:All>
- <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" /> 
  <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" /> 
  </sp:SignedParts>
- <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
  <sp:Body /> 
  </sp:EncryptedParts>
  </wsp:All>
  </wsp:ExactlyOne>
  </wsp:Policy>.
.
.
.
.
.
.
.
.
.
- <wsdl:service name="EntidadeServico">
- <wsdl:port name="WSHttpBinding_IEntidadeServico" binding="tns:WSHttpBinding_IEntidadeServico">
  <soap12:address location="http://172.16.4.95:8282/DadosCadastrais/EntidadeServico.svc" /> 
- <wsa10:EndpointReference>
  <wsa10:Address>http://172.16.4.95:8282/DadosCadastrais/EntidadeServico.svc</wsa10:Address> 
- <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
  <Spn>host/CARDHOM002.infradev.infraweb.redecard</Spn> 
  </Identity>
  </wsa10:EndpointReference>
  </wsdl:port>
- <wsdl:port name="NetTcpBinding_IEntidadeServico" binding="tns:NetTcpBinding_IEntidadeServico">
  <soap12:address location="net.tcp://cardhom002.infradev.infraweb.redecard/DadosCadastrais/EntidadeServico.svc" /> 
- <wsa10:EndpointReference>
  <wsa10:Address>net.tcp://cardhom002.infradev.infraweb.redecard/DadosCadastrais/EntidadeServico.svc</wsa10:Address> 
  </wsa10:EndpointReference>
  </wsdl:port>
  </wsdl:service>
  </wsdl:definitions>

Response:
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <s:Header>
    <a:Action s:mustUnderstand="1" u:Id="_2">http://tempuri.org/IEntidadeServico/ConsultarPorEmailSenhaHashResponse</a:Action>
    <a:RelatesTo u:Id="_3">urn:uuid:504c730f-aa8c-4874-8fb7-f99dcc62270c</a:RelatesTo>
    <ActivityId CorrelationId="3c086ef8-17e0-4812-97a5-c262938c51c1" xmlns="http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics">00000000-0000-0000-0000-000000000000</ActivityId>
    <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <u:Timestamp u:Id="uuid-528de796-88df-4244-b136-78c02fd3df11-11">
        <u:Created>2015-04-23T16:28:25.645Z</u:Created>
        <u:Expires>2015-04-23T16:33:25.645Z</u:Expires>
      </u:Timestamp>
      <c:DerivedKeyToken u:Id="uuid-528de796-88df-4244-b136-78c02fd3df11-7" xmlns:c="http://schemas.xmlsoap.org/ws/2005/02/sc">
        <o:SecurityTokenReference>
          <o:Reference URI="urn:uuid:97f54124-3fdf-4bce-b7bf-71d72a7cc4df" ValueType="http://schemas.xmlsoap.org/ws/2005/02/sc/sct" />
        </o:SecurityTokenReference>
        <c:Offset>0</c:Offset>
        <c:Length>24</c:Length>
        <c:Nonce>0TC73kpGmMdPFSb10XiwRQ==</c:Nonce>
      </c:DerivedKeyToken>
      <c:DerivedKeyToken u:Id="uuid-528de796-88df-4244-b136-78c02fd3df11-8" xmlns:c="http://schemas.xmlsoap.org/ws/2005/02/sc">
        <o:SecurityTokenReference>
          <o:Reference URI="urn:uuid:97f54124-3fdf-4bce-b7bf-71d72a7cc4df" ValueType="http://schemas.xmlsoap.org/ws/2005/02/sc/sct" />
        </o:SecurityTokenReference>
        <c:Nonce>rRvWrnj1AvR0orRYK1InJQ==</c:Nonce>
      </c:DerivedKeyToken>
      <e:ReferenceList xmlns:e="http://www.w3.org/2001/04/xmlenc#">
        <e:DataReference URI="#_1" />
        <e:DataReference URI="#_4" />
      </e:ReferenceList>
      <e:EncryptedData Id="_4" Type="http://www.w3.org/2001/04/xmlenc#Element" xmlns:e="http://www.w3.org/2001/04/xmlenc#">
        <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" />
        <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
          <o:SecurityTokenReference>
            <o:Reference ValueType="http://schemas.xmlsoap.org/ws/2005/02/sc/dk" URI="#uuid-528de796-88df-4244-b136-78c02fd3df11-8" />
          </o:SecurityTokenReference>
        </KeyInfo>
        <e:CipherData>
          <e:CipherValue>I1wb2g01kC1vSI53P5p949XD3iNWn2EIn0axQvfusTpfA9QtKRsqGLYhYL1DTLKI7XkcuBMNgZCsgCo1rz+ARXOKPw+RpDO2r3/+GUXFJrlv4caTvprdyDAUErM7X47tmSAboH5ofoimcGvnBCVNIvuN6Lw/+NbOGjqI7Oma0g2R1WOJZB3XYY6tJ7BKkK9VV4xg3ntUkyhjvlceT42q9mOTiw9KL3K+u5OBV652JA8Z9Xt48l+vcsH4KZg37aMxMRJVGIknz1m9SwsuT3xWYzPrhPkBFon8QbU/ot4guB372qjHVWqIa3WJWZzwR+QkLzD9eDPLKLi21n89XtpPqqhpuqwnIa3x50WvZrKpd+LVLyzCdnjAdoqTBq9KMHqxZGunfigInG5IgHzsLgtuTuSNJlcuXpHFCSPK+lAxy4XKzuLiuH+4agyTStTXy/Q+DjETueVbg5TlpBf5xO69TZiklaVmTrgWuSh1iPB9P6UtFUHlTryDxAyTlf6sDVFu6LH9PQIwnC9tML2e+T/oas5YF1x5Ph3m8LHQLchikhIG+m44Hq+3QKz2MrdjALLbkjRCpplj+Tsbc0PYByIYdNtF0yDaKPekDAq1qwjOcwDhX3J2NS0WoUezHfV+HcXDrwHvCquEmw/4IMZ1yrssxye/zsLwltu5DK+BxtjLG9+6cIdu0yHcj46UVEYTWvv5N9A7dQ52gTsNr81/nDQFJVfUNDqzXfpvIF3y0VzdXgrqiWFU6+G2hMOMaXf+g+vqFtyCAcpUAiggtU3jgEoTSdJh/94UH5eO6VZ+vsD//Ox5B7AKTQrbkSYuc2Jir5dNohu3H0mO8hBfggPkv9AE0FJz/BHaUHYYc/yBEeaO1YfiAd4yO1bVb+iqKpKxxZ4rgpOcuCEOx4mBnlEVvgSC5xKE1sZF3Wl5kazOP+4TAy2n+51RdqPHXYpvZA9tKURkZp9Go2D8yYUZA9WfmK7Cd3LONv26rcLsDknbwKfOs1ltCT5s5+ptVStvk7Cv86LMVCIGMejr13Nn1L3wXz4QNXal7z0oew8Rov+Y2HhkXLZSgcRoswycqsA5Z69UNDA42nKY73M5fTFVV8ZyTzIPGYAQ+dbSkrXSFXwO1VRiqCUIxvrzbJz1kGgi+dhZt9ljQxqljkJspH9ScZwNU4Z8gfabcI7cFLNwMruURSW5z2Jl9eEQ5robs9mUXMeTReZN3Ah1C5NOcgy5eifX80X0jWgPTDau/Ihp7rUirnF+Ekm5qoGFTJigBG5kq3gjagvQXjedGgZSBF3ZF4wJUxKqc10qF2qdp5HDAUDX5FFakF+tKHDr0ow85dc/7wW8PyXiSv2JXGDwAwF5ajevoPOma9a+ZAuuSW50tLL5uFqAs2mdXnmqmERG7Modqtfwuc+5CcEUZyeEnh+9L+qk3Ugp8RIVxiewHiM+/qptffHXFvZTKIpjsZ03j2C7X6G2iH4PoE78qwsJDtrSJQV4Tzu44Wb1fzbzniFJmAZKssmcL+QDmifMAyyTgZcLP1G4S8LWtDiy30T5DiCy6OIQRPNwYrSABeny0Vo01xV8guxBw+CefDZ8ePgG+SujLMGvlSZ3p4BX4E7rwCe8vEvhIF2iokCiW0xR4F89THXwh77B1cU++WHysLF0yDkJ5pqG9inpru2msfchEJg/V1iwhJjR76991f45kGMRUmugJSo31A0jWe1SPgBjqOIpK2dCA+aVbsZEuY3MMP1umkAJ2QV0Wr3E1fvAA3xzlYY3IQIRont6lQWrQP6vsQoVd+1kIdKJD3P7eGQI+WJ50Qfwi6F3NSngxpi1wWgygxUQWAXpktr/kKHhhuuxUMwrGB0xu5lfQbyb1kDwfkBlDjc9SF2WBik5srryfHsMHqooTwMYxTl4JtKCkjbcO+CoFbGx5+b/G4g4To4hKZXaqCP8iglwWvgsBdfy7h6+EJkUS/XpoZ1k/k+b9vYwJrUKwZNY0LD4lFaRzDPohmBCGYuKLHyySAfBxHZ05JAQ+0z/9z7ajGpZNySSKV5/7lEAeDelexekdzJtqmmKWI6Yp5TzXSN3hvvovlSiNjKLYI4tEwkzv41sb1DeNHotMrGsTEgBPJIc2AeKbHGo1L3PngPEW7FwtzqrRVebDIdm34fizjHT8WZLCmdFwPUpuS+sJZiiC0Xg</e:CipherValue>
        </e:CipherData>
      </e:EncryptedData>
    </o:Security>
  </s:Header>
  <s:Body u:Id="_0">
    <ConsultarPorEmailSenhaHashResponse xmlns="http://tempuri.org/">
      <ConsultarPorEmailSenhaHashResult xmlns:a="http://schemas.datacontract.org/2004/07/Redecard.PN.DadosCadastrais.Modelo" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" />
      <codigoRetorno>0</codigoRetorno>
    </ConsultarPorEmailSenhaHashResponse>
  </s:Body>
</s:Envelope>

**Comment by raymondfeng** [comment]
The SOAP response seems to have `ConsultarPorEmailSenhaHashResponse` as a child element of `Body`.

**Comment by cubissimo** [comment]
Thanks! 

but, what you suggest to do in this scenario? I sadly doe'nst have control to modify the service.

**Comment by raymondfeng** [comment]
Your post of WSDL is missing the sections that tell the portType/messages. Can you post it into a gist?

**Comment by cubissimo** [comment]
WSDL Gist -> https://gist.github.com/cubissimo/05a6e896880bdb116beb

**Comment by raymondfeng** [comment]
Which operation do you call, `ConsultarPorEmail` or `ConsultarPorEmailSenhaHash`?

 <wsdl:operation name="ConsultarPorEmail">
  <wsdl:input wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmail" message="tns:IEntidadeServico_ConsultarPorEmail_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmailResponse" message="tns:IEntidadeServico_ConsultarPorEmail_OutputMessage" /> 
  <wsdl:fault wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmailGeneralFaultFault" name="GeneralFaultFault" message="tns:IEntidadeServico_ConsultarPorEmail_GeneralFaultFault_FaultMessage" /> 
  </wsdl:operation>
- <wsdl:operation name="ConsultarPorEmailSenhaHash">
  <wsdl:input wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmailSenhaHash" message="tns:IEntidadeServico_ConsultarPorEmailSenhaHash_InputMessage" /> 
  <wsdl:output wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmailSenhaHashResponse" message="tns:IEntidadeServico_ConsultarPorEmailSenhaHash_OutputMessage" /> 
  <wsdl:fault wsaw:Action="http://tempuri.org/IEntidadeServico/ConsultarPorEmailSenhaHashGeneralFaultFault" name="GeneralFaultFault" message="tns:IEntidadeServico_ConsultarPorEmailSenhaHash_GeneralFaultFault_FaultMessage" /> 
  </wsdl:operation>

**Comment by cubissimo** [comment]
ConsultarPorEmailSenhaHash

**Comment by raymondfeng** [comment]
How does the request look like?

**Comment by cubissimo** [comment]
this is the request: https://gist.github.com/cubissimo/44187272204d32bbb4fe

**Comment by cubissimo** [comment]
some advice? i'm really stuck with this problem. 

thank you for your time.

**Comment by cubissimo** [comment]
I figured out the issue is on namespacing of node-soap lib. Too much repeated namespaces was causing the problem. I commented out the line in lib file client.js who include this namespaces and all got to work.

But this is not a good solution, can u guys suggest other way to do that?

**Comment by cubissimo** [comment]
I'm closing this issue because is no longer a problem.
