### ISSUE TITLE
Free to use?

### ISSUE THREAD

**Issue by jadbaz** [strongloop/loopback-connector-soap#23]
Hello,
I'm looking at the pricing list and I'm not sure I understand exactly where this package fits in.
Is this free to use?

I'm mainly using the SOAP connector:
```
var loopback = require('loopback');

var ds = loopback.createDataSource('soap',
  {
    connector: require('./index'),
    wsdl: 'http://www.webservicex.net/currencyconvertor.asmx?wsdl' // The url to WSDL
  });
```

Thank you

**Comment by phiat** [comment]
My guess this still falls under https://github.com/strongloop/loopback/blob/master/LICENSE.

**Comment by jadbaz** [comment]
Hmm,
I'm not sure how the MIT license option fits in with this: https://strongloop.com/node-js/subscription-plans/
The latter suggests that several services (including SOAP connector) are not free and require a subscription plan.

**Comment by rosshettel** [comment]
Well, the license for this repo doesn't include MIT: https://github.com/strongloop/loopback-connector-soap/blob/master/LICENSE.md

Also, the main loopback repo lists this package under [Enterprise Connectors](https://github.com/strongloop/loopback#enterprise-connectors), so it would seem that it's indeed not free to use

**Comment by jadbaz** [comment]
Thankfully, I found [node-soap](https://github.com/jadbaz/node-soap).
It's free and actually a much better package!
