### ISSUE TITLE
Default empty namespace absent

### ISSUE THREAD

**Issue by jadbaz** [strongloop/loopback-connector-soap#24]
Hello,
I have a service that has a schema that requires the following XML for actionA:

```
<actionA xmlns="http://ws.example.com/">
    <param1 xmlns="">ABC</uid>
    <param2 xmlns="">123</vendor>
    <param3 xmlns="">5</authentication>
</actionA>
```

The action element has a namespace, whereas the parameters are simply strings.
If I don't provide an empty namespace for them, they will take on the parent namespace (unless I'm misunderstanding XSD).
In any case, this is how my service expects the payload and this is how [wizdler](https://chrome.google.com/webstore/detail/wizdler/oebpmncolmhiapingjaagmapififiakb?hl=en) generates the skeletons, with an empty namespace.
However loopback generates the following which returns an exception:

```
<actionA xmlns="http://ws.example.com/">
    <param1>ABC</uid>
    <param2>123</vendor>
    <param3>5</authentication>
</actionA>
```

I'm dead sure that this is the only issue. When I simply add xmlns="" on the params it works.

How can I get loopback do that?

Thank you

**Comment by eddiemonge** [comment]
@jadbaz are the closing tags supposed to be `</param1>` instead of  `</uid>`?

**Comment by eddiemonge** [comment]
Seems like a feature request similar to #49

**Comment by nesrineBesbes** [comment]
This issue has not been resolved yet! 
I have a service  that has  the same schema as @jadbaz 
`<actionA xmlns:xsi="xsi URL " xmlns:xsd=" xsd URL">
    <a xsd:type="xsd:string">A</a>
     <b xsd:type="xsd:string">B</b>
    <c xsd:type="xsd:string">C</c>
</actionA>`


 so, with loopback 3 when I  add the "xsd URL" on all the  params, it works.
for example for the parameter  "a":
`a:{$attributes: { $xsiType: "{URL xsd}xsd:string",
 },
 $value: "A",
 }`

The loopback generate automatically "xsi URL"  and the XML request will be as following:
`<actionA>
<a:Valeur xmlns:xsi="URL xsi" 
		  xmlns:xsd="URL xsd" 
		  xsi:type="xsd:string">A<a/>
</actionA>`

How can I generate "xsi URL" and "xsd URL" only in the header  an not in params  through loopback, to get an xml request similar to the service schema ?
