### ISSUE TITLE
loopback soap connector - add xmlns to a namespace

### ISSUE THREAD

**Issue by Tojonirina4** [strongloop/loopback-connector-soap#49]
Hello,
Is it possible to add a xmlns attribute to a specific namespace with loopback soap connector ?
Issue : when converting a json to xml, loopback doesn't add the xmlns attribute to a tag which is an array.

**Comment by eddiemonge** [comment]
Related to or duplicate of #24

**Comment by evan-mcclaugherty** [comment]
This is a much needed feature for the salesforce marketing cloud wsdl.
