### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by Bramanga** [strongloop/loopback-connector-soap#7]
Does this connector support attachments? I have a soap endpoint that I am hitting, but the node-soap library that I'm using doesn't support attachments. Is there any way to do that here?

Cheers.

**Comment by longweiquan** [comment]
+1. There's not a pratical library in NodeJS for extracting the Soap attachments, hope that loopback can provide that.

Thanks !

**Comment by gunjpan** [comment]
@raymondfeng : Do we support this?
