### ISSUE TITLE
CI failed due to missing .travis.yml

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-soap#80]
CI failed due to missing `.travis.yml`.  
We should evaluate if there is a need to run Travis (if not, disable it), or to add the `.travis.yml` file. 

cc @bajtos @rashmihunt

**Comment by dhmlau** [comment]
@bajtos @rashmihunt, CI fails because of the missing `.travis.yml`.  Could you please evaluate whether we need to run the CI on travis?  If not, we can disable it.  Please let me know and I can do the corresponding fix.  Thanks.

**Comment by bajtos** [comment]
Travis CI has one big advantage compared to our internal CI setup: the test results are accessible by general public. So when a community contributor sends a pull request and the CI build fail, they can open Travis CI page to see the problems. This is not possible with our internal CI.

IMO, it's a good idea to enable Travis CI for this repository.

**Comment by dhmlau** [comment]
PR has landed.  Closing it.
