### ISSUE TITLE
WSDL url http auth 

### ISSUE THREAD

**Issue by MpEliaz** [strongloop/loopback-connector-soap#92]
Hi guys, I have a problem getting the WSDL because the endpoint has to http basic auth. and i don't have idea where put the credentials for to generate the api. (in the model or datasource json file)

(sorry my english).

**Comment by gizmo84** [comment]
Hi @MpEliaz . From the doc at https://loopback.io/doc/en/lb3/SOAP-connector.html#security-property you have to set the security object in datasources.json.

**Comment by ilijaz** [comment]
I've spent 2 hours reading docs and debugging.
You should use "wsdl_headers" option in datasource config for sending custom http headers
```
    "wsdl_headers": {
      "Authorization": "Basic UGVyc29uYWwgYWNjb3VudDpORVdsazIwMTVAKSEl"
    },

```
By the way, security option object is used only for methods not for wsdl requests.

**Comment by Realetive** [comment]
Add information about it to README.md — https://github.com/strongloop/loopback-connector-soap/pull/107

**Comment by ilijaz** [comment]
@Realetive I'm not sure about #107. BasicAuth security scheme is supported. If your soap source has http basic auth you should use both wsdl_headers and security scheme options in the datasource config.
