### ISSUE TITLE
Unit tests failed (Invalid WSDL URL)

### ISSUE THREAD

**Issue by 3z3qu13l** [strongloop/loopback-connector-soap#93]
# Description
Hello guys,

I just cloned the repo and unit tests failed due to invalid WSDL URL.
Got 404 on this: http://www.webservicex.net/stockquote.asmx?wsdl

As a result several tests return an error.

# Steps to reproduce
```
git clone https://github.com/strongloop/loopback-connector-soap.git
cd loopback-connector-soap
npm i
npm test
```

**Comment by dhmlau** [comment]
@3z3qu13l , unfortunately, that web service is not available anymore before we have the chance to fix the test cases.  Would you be interested in submitting a PR for that?

**Comment by 3z3qu13l** [comment]
Hello @dhmlau ,

I fixed the unit tests using this public WSDL: http://ws.cdyne.com/emailverify/Emailvernotestemail.asmx?wsdl

I didn't update dependencies but there are a few ones that could be updated:
Package           Current  Wanted  Latest  Location
debug               2.6.9   2.6.9   3.1.0  loopback-connector-soap
mocha               3.5.3   3.5.3   5.2.0  loopback-connector-soap
should                9.0.2   9.0.2  13.2.1  loopback-connector-soap
strong-globalize   2.10.0  2.10.0   4.1.1  loopback-connector-soap

Maybe it would be nice to update them in another PR along with const/let refactor.

**Comment by dhmlau** [comment]
@3z3qu13l , thanks for your contribution.  Since your PR has landed, is this ticket ok to close?  Thanks.

**Comment by 3z3qu13l** [comment]
Yes absolutely
